Added support for building 32bit on 64bit machines

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19,33 +19,40 @@
 ##  this program.  If not, see <http://www.gnu.org/licenses/>.
 ##
 ###-----------------------------------------------------------------------------
-### Description: system configuration
-###-----------------------------------------------------------------------------
-##  To use a pre-installed version of the Boehm memory management system
-##  set EUL_GC_DIR to its directory.
+### Options:
+##    The system archicecture may be specified as an argument
+##    which overrides the default
+### Description:
+##    To use a pre-installed version of the Boehm memory management system
+##    set EUL_GC_DIR to its directory.
 ##
-##  Give an empty gabage collector directory if you don't want to use the
-##  garbage collector at all. This is not recommended as you will have
-##  performace drawbacks.
+##    Give an empty gabage collector directory if you don't want to use the
+##    garbage collector at all. This is not recommended as you will have
+##    performace drawbacks.
 ##
-##  Set CC if you prefer a particular C compiler.
+##    Set CC if you prefer a particular C compiler.
 ##
-##  See the relevant section in this file for information about using an
-##  external thread library (e.g. Solaris threads).
+##    See the relevant section in this file for information about using an
+##    external thread library (e.g. Solaris threads).
 ###-----------------------------------------------------------------------------
 
 ###-----------------------------------------------------------------------------
-### Lookup platform
+### Set platform and architecture
 ###-----------------------------------------------------------------------------
-
 OSTYPE=`uname -s`
-ARCH=`uname -m`
+
+# Check for the command-line architecture option
+if [ $# = 1 ]
+then
+    ARCH=$1
+else
+    ARCH=`uname -m`
+fi
 
 ###-----------------------------------------------------------------------------
 ### Set version, default current installation, bootstrapping installation
 ##  and GC installation directories
 ###-----------------------------------------------------------------------------
-
 EUL_VERSION=pre-0.991
 
 EUL_DIR=`pwd`
@@ -57,7 +64,6 @@ EUL_BOOT_DIR=${EUL_DIR}.boot
 ### C compiler
 ##  leave blank to selected automatically
 ###-----------------------------------------------------------------------------
-
 CC=
 
 ###-----------------------------------------------------------------------------
@@ -67,13 +73,11 @@ CC=
 ##    eemacs is the version used here which includes a more recent
 ##    org-mode than released with emacs.
 ###-----------------------------------------------------------------------------
-
 EMACS=eemacs
 
 ###-----------------------------------------------------------------------------
 ### Specify the default shell and where to find mv and rm
 ###-----------------------------------------------------------------------------
-
 EUL_SHELL=/bin/sh
 UNIX_DIR=/bin
 
@@ -87,7 +91,6 @@ UNIX_DIR=/bin
 ##    PPCR (POSIX Portable Common Runtime)
 ##    MIT (MIT Pthread Library)
 ###-----------------------------------------------------------------------------
-
 THRTYPE=DEFAULT
 #THRTYPE=UI
 #THRTYPE=PPCR
@@ -97,7 +100,6 @@ THRTYPE=DEFAULT
 ###-----------------------------------------------------------------------------
 ### Set paths for Youtoo, binaries, scripts and libraries
 ###-----------------------------------------------------------------------------
-
 U2_DIR=$EUL_DIR/Youtoo
 EUL_BIN_DIR=$EUL_DIR/Bin.$ARCH
 EUL_LIB_DIR=$EUL_DIR/Lib.$ARCH
@@ -107,24 +109,25 @@ EUL_LIB_DIR=$EUL_DIR/Lib.$ARCH
 ##    EUL_BOOT_DIR can be set to EUL_DIR which will use the current local build
 ##    and over-write it during the build
 ###-----------------------------------------------------------------------------
-
 EUL_BOOT_BIN_DIR=$EUL_BOOT_DIR/Bin.$ARCH
 
 ###-----------------------------------------------------------------------------
 ### Verify the some settings
 ###-----------------------------------------------------------------------------
-
 FOO=$EUL_VERSION
 touch ./$FOO
-if (test ! -f ${EUL_DIR}/${FOO}) then
+if [ ! -f ${EUL_DIR}/${FOO} ]
+then
     echo "*** ERROR [configure]: bad EUL_DIR directory: " ${EUL_DIR}
     rm ./$FOO
     exit
 fi
 rm ./$FOO
 
-if (test ! -z "$EUL_GC_DIR") then
-    if (test ! -d $EUL_GC_DIR) then
+if [ ! -z "$EUL_GC_DIR" ]
+then
+    if [ ! -d $EUL_GC_DIR ]
+    then
         echo "*** ERROR [configure]: bad EUL_GC_DIR directory: " $EUL_GC_DIR
     fi
 fi
@@ -134,12 +137,13 @@ EUL_GC_INCLUDE="-I${EUL_GC_DIR} -I${EUL_GC_DIR}/include"
 ###-----------------------------------------------------------------------------
 ### Set CC if currently unset
 ###-----------------------------------------------------------------------------
-
-if (test -z "$CC") then
+if [ -z "$CC" ]
+then
     gcc_path=`which gcc 2>/dev/null`
     gcc=`basename "${gcc_path}"`
 
-    if (test "$gcc" = gcc) then
+    if [ "$gcc" = gcc ]
+    then
         CC=gcc
         CFLAGS="-std=gnu99 -Wall -Wno-sequence-point -fPIC -O3 -fno-strict-aliasing"
     else
@@ -151,21 +155,18 @@ fi
 ###-----------------------------------------------------------------------------
 ### Set basic flags and libraries
 ###-----------------------------------------------------------------------------
-
 CLIBS="-leval -lmath -llevel1 -llevel-0 -leval -ltelos -lboot -leulvm -lm"
 CFLAGS="$CFLAGS -I${U2_DIR}/include -I${U2_DIR}/Vm"
 
 ###-----------------------------------------------------------------------------
 ### Readline library (optional)
 ###-----------------------------------------------------------------------------
-
 CFLAGS="$CFLAGS -DREADLINE"
 CLIBS="$CLIBS -lreadline"
 
 ###-----------------------------------------------------------------------------
 ### Tcl/Tk libraries
 ###-----------------------------------------------------------------------------
-
 EUL_TK_VERSION=8.5
 EUL_TK_FLAGS=
 
@@ -176,62 +177,81 @@ EUL_TK_FLAGS=
 ###-----------------------------------------------------------------------------
 ###  Linux
 ###-----------------------------------------------------------------------------
-
 case $OSTYPE in
 Linux)
-    if (test $ARCH = x86_64) then
+    if [ $ARCH = x86_64 ]
+    then
         WORD_LENGTH=64
-    else
+    elif [ $ARCH = i686 ]
+    then
         WORD_LENGTH=32
+    else
+        echo "*** ERROR [configure]: unknown $OSTYPE system type $ARCH" >&2
+        exit
     fi
 
     CC="gcc"
     AR="ar cruv"
     RANLIB="ranlib"
+    CFLAGS="$CFLAGS -m$WORD_LENGTH"
 
-    if (test $THRTYPE = PPCR) then
+    if [ $THRTYPE = PPCR ]
+    then
         CFLAGS="$CFLAGS -DWITH_PCR_TREADS -I${EUL_GC_DIR}/posix -I${EUL_GC_DIR} -I${EUL_GC_DIR}/include -I${EUL_GC_DIR}/gc"
     else
         CFLAGS="$CFLAGS ${EUL_GC_INCLUDE}"
         CLIBS="$CLIBS -lpthread"
     fi
+
+    EUXLISP_CFLAGS="-m$WORD_LENGTH -DWORD_LENGTH=$WORD_LENGTH -std=gnu99 -Wall -O3 -DSIGNAL -DSTRINGH -DREADLINE"
+    EUXLISP_LIBS="-m$WORD_LENGTH -lm -lreadline"
     ;;
 
 ###-----------------------------------------------------------------------------
 ###  FreeBSD
 ###-----------------------------------------------------------------------------
-
 FreeBSD)
-    if (test $ARCH = x86_64) then
+    if [ $ARCH = x86_64 ]
+    then
         WORD_LENGTH=64
-    else
+    elif [ $ARCH = i686 ]
+    then
         WORD_LENGTH=32
+    else
+        echo "*** ERROR [configure]: unknown $OSTYPE system type $ARCH" >&2
+        exit
     fi
 
     CC="gcc"
     AR="ar cruv"
     RANLIB="ranlib"
+    CFLAGS="$CFLAGS -m$WORD_LENGTH"
 
-    if (test $THRTYPE = PPCR) then
+    if [ $THRTYPE = PPCR ]
+    then
         CFLAGS="$CFLAGS -DWITH_PCR_TREADS -I${EUL_GC_DIR}/posix -I${EUL_GC_DIR}  -I${EUL_GC_DIR}/gc"
     else
         CFLAGS="$CFLAGS ${EUL_GC_INCLUDE}"
     fi
+
+    EUXLISP_CFLAGS="-m$WORD_LENGTH -DWORD_LENGTH=$WORD_LENGTH -std=gnu99 -Wall -O3 -DSIGNAL -DSTRINGH -DREADLINE"
+    EUXLISP_LIBS="-m$WORD_LENGTH -lm -lreadline"
     ;;
 
 ###-----------------------------------------------------------------------------
 ###  SunOS (Solaris)
 ###-----------------------------------------------------------------------------
-
 SunOS)
     WORD_LENGTH=64
-    if (test $THRTYPE = UI) then
+    if [ $THRTYPE = UI ]
+    then
         CC="cc"
         CFLAGS="$CFLAGS -DWITH_STRERROR -DWITH_UI_THREADS ${EUL_GC_INCLUDE}"
         CLIBS="$CLIBS -lnls -lnsl -lsocket -ldl -lthread"
         AR="ar crsuv"
         RANLIB="echo No ranlib "
-    elif (test $CC = gcc) then
+    elif [ $CC = gcc ]
+    then
         CFLAGS="$CFLAGS -fPIC -DWITH_STRERROR ${EUL_GC_INCLUDE}"
         CLIBS="$CLIBS -lnls -lnsl -lsocket"
         AR="ar crsuv"
@@ -247,21 +267,23 @@ SunOS)
 ###-----------------------------------------------------------------------------
 ###  IRIX
 ###-----------------------------------------------------------------------------
-
 IRIX)
     WORD_LENGTH=64
-    if (test $THRTYPE = PPCR) then
+    if [ $THRTYPE = PPCR ]
+    then
         CC="cc"
         CFLAGS="$CFLAGS -Olimit 4000 -common -DWITH_PCR_THREADS -I${EUL_GC_DIR}/posix -I${EUL_GC_DIR}/gc"
         AR="ar crsuv"
         RANLIB="echo No ranlib "
-    elif (test $THRTYPE = MIT) then
+    elif [ $THRTYPE = MIT ]
+    then
         CC="gcc"
         CFLAGS="$CFLAGS -DMIT_PTHREADS -I${EUL_GC_DIR} -I${EUL_GC_DIR}/include -I${EUL_MIT_THR_DIR}/include -L${EUL_MIT_THR_DIR}/obj"
         CLIBS="-lpthread $CLIBS -lgcc -lpthread"
         AR="ar crsuv"
         RANLIB="echo No ranlib "
-    elif (test $CC = gcc) then
+    elif [ $CC = gcc ]
+    then
         CFLAGS="$CFLAGS ${EUL_GC_INCLUDE}"
         AR="ar crsuv"
         RANLIB="echo No ranlib "
@@ -273,36 +295,20 @@ IRIX)
     ;;
 
 ###-----------------------------------------------------------------------------
-###  Microsoft Windows NT/2k using Cygwin
-###-----------------------------------------------------------------------------
-
-CYGWIN_NT-5.0)
-    if (test $ARCH = x86_64) then
-        WORD_LENGTH=64
-    else
-        WORD_LENGTH=32
-    fi
-    CC="gcc"
-    CFLAGS="$CFLAGS -DWITH_STRERROR ${EUL_GC_INCLUDE}"
-    AR="ar cruv"
-    RANLIB="ranlib"
-    ;;
-
-###-----------------------------------------------------------------------------
 ###  IBM AIX
 ###-----------------------------------------------------------------------------
-
 AIX)
     WORD_LENGTH=64
     CFLAGS="$CFLAGS ${EUL_GC_INCLUDE} -DWITH_STRERROR"
     AR="ar cruv"
     RANLIB="ranlib"
+    EUXLISP_CFLAGS="-D_ALL_SOURCE -DSOCK"
+    EUXLISP_LIBS="-lm"
     ;;
 
 ###-----------------------------------------------------------------------------
 ###  Unknown
 ###-----------------------------------------------------------------------------
-
 *)    # an unsupported operating system
     echo "*** ERROR [configure]: unknown system type $OSTYPE" >&2
     exit
@@ -318,19 +324,16 @@ EUL_ARCH_OP=-DEUL_ARCH='\"'$ARCH'\"'
 ###-----------------------------------------------------------------------------
 ### Set word-length option
 ###-----------------------------------------------------------------------------
-
 WORD_LEN_OP=-DWORD_LENGTH=$WORD_LENGTH
 
 ###-----------------------------------------------------------------------------
 ### Make scripts executable
 ###-----------------------------------------------------------------------------
-
 chmod ug+x ${U2_DIR}/Tools/make*.*
 
 ###-----------------------------------------------------------------------------
 ### Prompting configuration
 ###-----------------------------------------------------------------------------
-
 echo "CONFIGURING youtoo ..."
 echo "  Dir: $EUL_DIR"
 echo "  Architecture: $ARCH"
@@ -345,20 +348,20 @@ echo "  Threads: $THRTYPE"
 ###-----------------------------------------------------------------------------
 ### Create Lib and Bin directory
 ###-----------------------------------------------------------------------------
-
-if (test ! -d $EUL_LIB_DIR) then
+if [ ! -d $EUL_LIB_DIR ]
+then
     mkdir $EUL_LIB_DIR
     cp Youtoo/Lib/lib*.i $EUL_LIB_DIR
 fi
 
-if (test ! -d $EUL_BIN_DIR) then
+if [ ! -d $EUL_BIN_DIR ]
+then
     mkdir $EUL_BIN_DIR
 fi
 
 ###-----------------------------------------------------------------------------
 ### Create resource file
 ###-----------------------------------------------------------------------------
-
 name_rc=${EUL_DIR}/.eulrc.${ARCH}
 echo "  Creating ${EUL_DIR}/.eulrc.${ARCH} ..."
 echo ";;; Copyright 1997 A. Kind & University of Bath" > $name_rc
@@ -382,7 +385,6 @@ echo \) >> $name_rc
 ###-----------------------------------------------------------------------------
 ### Create Makefile header
 ###-----------------------------------------------------------------------------
-
 name=${EUL_LIB_DIR}/Makefile
 echo "  Creating ${EUL_LIB_DIR}/Makefile ..."
 echo "### Copyright 1997 A. Kind & University of Bath" > $name
@@ -394,6 +396,7 @@ echo "###-----------------------------------------------------------------------
 echo >> $name
 echo CC = ${CC} >> $name
 echo "CFLAGS = ${WORD_LEN_OP} ${EUL_DIR_OP} ${EUL_ARCH_OP} ${CFLAGS}" >> $name
+echo "EUXLISP_CFLAGS = ${EUXLISP_CFLAGS}" >> $name
 echo 'ARCH_DIR = platforms/$(ARCH)' >> $name
 echo '.PRECIOUS: %/.' >> $name
 echo '%/.:' >> $name
@@ -404,6 +407,7 @@ echo '$(ARCH_DIR)/%.o : %.c | $(ARCH_DIR)/.' >> $name
 echo '	mkdir -p $(@D)' >> $name
 echo '	$(CC) -c $(CFLAGS) $(CPPFLAGS) $< -o $@' >> $name
 echo CLIBS = ${CLIBS} >> $name
+echo "EUXLISP_LIBS = ${EUXLISP_LIBS}" >> $name
 echo AR = ${AR} >> $name
 echo RANLIB = ${RANLIB} >> $name
 echo ARCH = ${ARCH} >> $name
@@ -437,21 +441,26 @@ echo >> $name
 ###-----------------------------------------------------------------------------
 ### Create link to GC library (if available)
 ###-----------------------------------------------------------------------------
-
-if (test -f $EUL_LIB_DIR/libgc.a) then
+if [ -f $EUL_LIB_DIR/libgc.a ]
+then
     rm -f $EUL_LIB_DIR/libgc.a
 fi
-if (test -f $EUL_LIB_DIR/libgc.so) then
+if [ -f $EUL_LIB_DIR/libgc.so ]
+then
     rm -f $EUL_LIB_DIR/libgc.so
 fi
-if (test -f Vm/gc.h) then
+if [ -f Vm/gc.h ]
+then
     rm -f Vm/gc.h
 fi
 
-if (test ! -z "${EUL_GC_DIR}") then
-    if (test $THRTYPE = PPCR) then
+if [ ! -z "${EUL_GC_DIR}" ]
+then
+    if [ $THRTYPE = PPCR ]
+    then
         ln -s ${EUL_GC_DIR}/base/libpcr.a $EUL_LIB_DIR/libgc.a
-    elif (test -f ${EUL_GC_DIR}/gc.a) then
+    elif [ -f ${EUL_GC_DIR}/gc.a ]
+    then
         ln -s ${EUL_GC_DIR}/gc.a $EUL_LIB_DIR/libgc.a
     fi
 else
@@ -462,7 +471,6 @@ fi
 ###-----------------------------------------------------------------------------
 ### Create youtoo scheme and check scripts
 ###-----------------------------------------------------------------------------
-
 create_script(){
     name=${EUL_BIN_DIR}/$1.sh
     echo "  Creating $name ..."
@@ -489,7 +497,6 @@ create_script check
 ###-----------------------------------------------------------------------------
 ### Create script to set LD_LIBRARY_PATH
 ###-----------------------------------------------------------------------------
-
 name=${EUL_BIN_DIR}/makeso.Path
 echo "  Creating makeso.Path ..."
 echo > $name
